= Oracle Certified Professional Java SE 17 1Z0-829 Open Study Guide
:imagesdir: images
:source-highlighter: highlightjs
:toc: left
:toclevels: 4

== About this book

This book's primary purpose is to provide a straightforward and convenient way to prepare for the new Oracle exam - 1z0-829.
This book assumes that you already have experience with java because the information in some chapters is very concentrated.

=== What is OCP?

This is professional JAVA https://education.oracle.com/java-se-17-developer/pexam_1Z0-829[certification] from Oracle.
You can use it as proof of your knowledge to your new employer.
There is a lot of controversy about whether it is necessary or not.
I believe that certification is necessary.
It gives you the possibility to structure your knowledge of java core.

=== What is Java 17?

Java 17 is LTS release.
It stands for Long Time Support version.
So, support for this version will continue until the end of 2026.
The following Java 21 LTS release will appear in September 2023. Until it, you will have up-to-date certification.

=== How to use this book

Book has 11 significant chapters.
Each chapter corresponds to a specific topic in the Oracle exam.
Each topic describes a problem in a maximum compressed format.
The topics are loosely connected to study them in any order.

=== Handing date, time, text, numeric and boolean values

==== Math API

==== Text Blocks

==== Date-Time API

=== Controlling Program Flow

==== Switch statements and expressions

===== Switch expressions

*Problem*: switch blocks effectively replace the expression if-else, but they are very verbose.
It's very likely to forget the BREAK word at the end of an expression.
And it couldn't return values.

*Solution*: switch expression with lambda look syntax.

Let's see an example.
We want to write a function that returns String with animal sound:

[source,java]
----
public enum Animal {
    DOG,
    CAT,
    LION,
    BIRD;

    public String getSound(Animal animal) {
        return switch (animal) {
            case CAT, LION -> "Meow";
            case DOG -> "Bark-Bark";
            case BIRD -> "Chick-Chick";
        };
    }
}
----

You should agree.
The expression looks much more compact than the standard switch.
We could add default case for unpredictable inputs:

[source,java]
----
return switch (animal) {
    case CAT -> "Meow";
    case DOG -> "Bark-Bark";
    case BIRD -> "Chick-Chick";
    default -> "Unknown animal";
};
----

In this case, our switch expression doesn't cover all possible enum values, so we add a default case, like in the old-fashioned switch.
If we want to add more instructions in our lambda, we need to add curvy bracers and a new reserved word yield:

[source,java]
----
return switch (animal) {
    case CAT -> "Meow";
    case DOG -> "Bark-Bark";
    case BIRD -> {
        System.out.println("It's a Bird!");
        yield "Chick-Chick";
    }
    default -> "Unknown animal";
};
----

Why don't we use return?
Because return will throw us out of the expression.

As a usual switch, a new switch consumes such objects:
*char, byte, short, int, Character, Byte, Short, Integer, String, or an enum.*

=== Utilizing Java Object-Oriented Approach

==== Create classes and records

==== Implement inheritance, including abstract and sealed classes

===== Sealed classes

*Problem*: Inheritance in Java is not limited.

For example, you have abstract class Animal, and your use it as a base class to build other classes like Dog and Cat.
But if someone creates a new class Car and decides to inherit it from Animal, you couldn't prevent it.

*Solution*: Sealed classes in Java 17.

Sealed classes enforce rules on inheritance:
[source,java]

----

public abstract sealed class Animal permits Dog, Cat {}
----

Now, only two classes can extend our base class.
We couldn't write such code:
[source,java]

----

public class Lion extends Animal {}
----

We need to add Lion class explicitly to Animal class signature, or we could get an error:

[source,bash]
----
java: class is not allowed to extend sealed class: dev.ivanov.book.Animal (as it is not listed in its permits clause)
----

Now, let's look at Cat and Dog classes.
We should mandatorily create them to compile our code.

Because we want to restrict inheritance, we need to foresee a situation where someone wants to inherit from our Cat and Dog classes to get functionality from the parent class.
And Java 17 gives us this possibility.
When we create Cat or Dog, we need to make these classes final - it prevents any inheritance from this class or mark them also sealed:

[source,java]
----

public final class Dog extends Animal {}
----

[source,java]
----

public sealed class Cat extends Animal permits Lion {}
----

Only the new Lion class can extend Cat.
In this way, we have protected the logic within our Cat class from erroneous inheritance.

In the case where such protection is not needed, and we want to give users unlimited inheritance options, it is worth adding the keyword non-sealed:

[source,java]
----

public non-sealed class Lion extends Cat {}
----

Now, class Lion may have any heirs.

It is especially worth noting that you can reduce the signature of a base class by simply putting all its descendants into the same file:
[source,java]

----

public abstract sealed class Animal {}
final class Bird extends Animal {}
----

Also, interfaces could be marked sealed:

[source,java]
----

public sealed interface Animal permits Bird, Cat, Dog {}
final class Bird implements Animal {}
----

But in this situation, we need explicitly declare all permits.

==== Instanceof operator and pattern matching

=== Access databases using JDBC

==== Control transactions using JDBC API
